---
title: "random_forest_model"
author: "Prashit Parikh"
date: "11/01/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
chooseCRANmirror(graphics=FLASE, ind=1)
knitr::opts_chunk$set(echo = TRUE)

install.packages("randomForest")
library(randomForest)
install.packages("caret")
library(caret)
install.packages("tidyverse")
library(tidyverse)
```

```{r, warning=FALSE}
# Imported from the create_regression_data.R script output
data <- read.csv("inference_regression_data.csv")
# View our variable of interest
data$sex %>% table()

# Split the data into an experiment and training set

set.seed(1020)
experiment.samples <- data$sex %>% 
  createDataPartition(p = 0.5, list = FALSE)
training.data  <- data[experiment.samples, ]
experiment.data <- data[-experiment.samples, ]

# Split the training set into a train and test set

set.seed(1020)
training.samples <- training.data$sex %>% 
  createDataPartition(p = 0.5, list = FALSE)
train.data <- data[training.samples, ]
test.data <- data[-training.samples, ]

# Run random forest

rf <- randomForest(as.factor(sex) ~ ., data=train.data, proximity=TRUE)
print(rf)

# Predictions - train
p1 <- predict(rf, train.data)
confusionMatrix(p1, as.factor(train.data$sex))

# Predictions - test
p2 <- predict(rf, test.data)
confusionMatrix(p2, as.factor(test.data$sex))

# Predictions - experiment
p3 <- predict(rf, experiment.data)
confusionMatrix(p3, as.factor(experiment.data$sex))
```
